name: 'Rearm Build And Submit Release metadata action'
description: 'Rearm Build And Submit Release metadata action'
branding:
  icon: 'anchor'
  color: 'green'
inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  registry_host:
    description: "Host for image registry"
    default: null
    required: false
  image_namespace:
    description: "Namespace of the image on registry"
    required: true
  image_name:
    description: "Name of the image"
    required: true
  rearm_api_id:
    description: "ReARM API ID"
    required: true
  rearm_api_key:
    description: "ReARM API KEY"
    required: true
  rearm_api_url:
    description: "ReARM API URL"
    required: false
    default: 'https://demo.rearmhq.com'
  path:
    description: "Path to the relative to root of the repo (default is '.')"
    required: false
    default: .
  dockerfile_name:
    description: "Name of the dockerfile (default is 'Dockerfile')"
    required: false
    default: Dockerfile
  ci_metadata:
    description: "Metadata for CI run, (Optional - default is GitHub)"
    required: false
  rearm_component_id:
    description: "Component UUID for this release if org-wide key is used"
    required: false
  push_latest_tag:
    description: "set to false if you do not want image tagged latest to be pushed"
    required: false
    default: 'true'
  platform_architectures:
    description: "comma separated list of platform architectures you want to build the image for, default is linux/amd64"
    required: false
    default: 'linux/amd64'
  enable_sbom:
    required: false
    default: 'false'
    description: Generates SBOM and stores it along with the artifact
  source_code_sbom_type:
    required: false
    default: 'none'
    description: "Generates SBOM based on source code analysis, possible values: npm, other, none"
  enable_public_cosign_sigstore:
    required: false
    default: 'false'
    description: "Sign deliverables and SBOMs using public sigstore via cosign"
  enable_codeql:
    required: false
    default: 'false'
    description: "Enable CodeQL analysis"
  codeql_language:
    required: false
    default: 'none'
    description: "Language to analyze with CodeQL"
  successful_build_lifecycle:
    required: false
    default: 'ASSEMBLED'
    description: "Status on build success to be set on ReARM (DRAFT or ASSEMBLED)"
  enable_securesbom:
    required: false
    default: 'false'
    description: "Enable SecureSBOM by ShiftLeftCyber signing of SBOMs"
  securesbom_pub_key_id:
    required: false
    default: ''
    description: "Public key id to sign with SecureSBOM by ShiftLeftCyber"
  securesbom_host:
    required: false
    default: ''
    description: "SecureSBOM (by ShiftLeftCyber) host"
  securesbom_api_key:
    required: false
    default: ''
    description: "SecureSBOM (by ShiftLeftCyber) API key"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0 
    - id: setup-rearm
      name: setup-rearm
      uses: relizaio/setup-rearm-cli-action@c13e9de63cca5fdc18c72a7cded3e6a27d041d13 # v1.2.1
    - name: Display rearm version
      shell: bash
      run: rearm version
    - id: rearm-initialize
      name: Initialize ReARM Flow
      uses: relizaio/rearm-initialize@main # v1.0.0 - experimental
      with: 
        rearm_api_id: ${{ inputs.rearm_api_id }}
        rearm_api_key: ${{ inputs.rearm_api_key }}
        rearm_api_url: ${{inputs.rearm_api_url}}
        repo_path: ${{inputs.path}}
        component: ${{inputs.rearm_component_id}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
    - name: Login to Docker Hub
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      if: ${{ inputs.registry_host == null }}
      with:
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}
    - name: Login to other Docker Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      if: ${{ inputs.registry_host != null }}
      with:
        registry: ${{inputs.registry_host}}
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}
    - name: Validate input list
      shell: bash
      run: |
        supported_platforms=('linux/amd64' 'linux/arm64' 'linux/s390x' 'linux/arm/v7' 'linux/arm/v6')
        input_list=($(echo '${{ inputs.platform_architectures }}' | tr ',' '\n'))
        if [[ -z "$input_list" ]]; then
          echo "Platform architectures list is empty"
          exit 1
        fi
        # Check if each element of the input list exists in the enum list
        for element in "${input_list[@]}"; do
        found=0
        for platform in "${supported_platforms[@]}"; do
          if [[ $platform == $element ]]; then
            found=1
            break
          fi
        done
        if [ $found -eq 0 ]; then
          echo "$element is not a supported platform"
          exit 1
        fi
        done
    - name: Build and push docker container to Rearm Hub Registry
      shell: bash
      if: ${{env.REARM_DO_BUILD == 'true'}}
      continue-on-error: true
      run: |
        cd ${{ github.workspace }}
        cd ${{ inputs.path }}
        
        branch_name=${{github.ref_name}}
        safe_branch_name=$(echo -n $branch_name | tr -dc '[:alnum:]-_.')
        case $safe_branch_name in

          master | main)
            latest_tag=latest
            ;;

          *)
            latest_tag=$safe_branch_name
            ;;
        esac

        tags="-t ${{inputs.image_namespace}}/${{inputs.image_name}}:${{ steps.rearm-initialize.outputs.short_version }}"

        if [ "${{inputs.push_latest_tag}}" == "true" ]
        then
          tags+=" -t ${{inputs.image_namespace}}/${{inputs.image_name}}:$latest_tag"
        fi

        # push branch tag for main or master
        if [ "$latest_tag" != "$safe_branch_name" ]
        then
          tags+=" -t ${{inputs.image_namespace}}/${{inputs.image_name}}:$safe_branch_name"
        fi
        echo "Building for platforms: ${{ inputs.platform_architectures }}"
        docker \
          buildx build --push --platform ${{ inputs.platform_architectures }} \
          $tags \
          --build-arg VERSION=${{ steps.rearm-initialize.outputs.full_version }} \
          --build-arg CI_ENV=github${{github.sha}} \
          --build-arg GIT_COMMIT=${{github.sha}} \
          --build-arg GIT_BRANCH=${{github.ref_name}} \
          -f ${{inputs.dockerfile_name}} .
          
        
        # buildx_inspect=$(docker buildx imagetools inspect ${{inputs.image_namespace}}/${{inputs.image_name}}:$latest_tag)
        # echo $buildx_inspect
        docker_sha_256=$(docker buildx imagetools inspect --format "{{json .Manifest}}" ${{inputs.image_namespace}}/${{inputs.image_name}}:${{ steps.rearm-initialize.outputs.short_version }} | jq -r '.digest')
       
        # save sha256 to env var
        echo "DOCKER_SHA_256=$docker_sha_256" >> $GITHUB_ENV
        echo "REARM_BUILD_LIFECYLE=${{inputs.successful_build_lifecycle}}" >> $GITHUB_ENV
    - name: Submit metadata to ReARM
      uses: relizaio/rearm-add-release@d40cd001b969b385e0f5ad34e0f770d93df3a179 # v1.5.1
      if: ${{env.REARM_DO_BUILD == 'true'}}
      with:
        rearm_api_id: ${{ inputs.rearm_api_id }}
        rearm_api_key: ${{ inputs.rearm_api_key }}
        rearm_api_url: ${{inputs.rearm_api_url}}
        image_full_name: ${{inputs.image_namespace}}/${{inputs.image_name}}
        image_digest: $DOCKER_SHA_256
        rearm_full_version: ${{ steps.rearm-initialize.outputs.full_version }}
        rearm_short_version: ${{ steps.rearm-initialize.outputs.short_version }}
        rearm_build_start: ${{ steps.rearm-initialize.outputs.build_start }}
        last_commit: ${{ steps.rearm-initialize.outputs.last_commit }}
        rearm_build_status: $REARM_BUILD_LIFECYLE
        rearm_component_id: ${{inputs.rearm_component_id}}
        enable_sbom: ${{inputs.enable_sbom}}
        source_code_sbom_type: ${{inputs.source_code_sbom_type}}
        registry_username: ${{inputs.registry_username}}
        registry_password: ${{inputs.registry_password}}
        registry_host: ${{inputs.registry_host}}
        path: ${{inputs.path}}
        enable_public_cosign_sigstore: ${{inputs.enable_public_cosign_sigstore}}
        enable_codeql: ${{inputs.enable_codeql}}
        codeql_language: ${{inputs.codeql_language}}
        finalize_release: "true"
        enable_securesbom: ${{inputs.enable_securesbom}}
        securesbom_pub_key_id: ${{inputs.securesbom_pub_key_id}}
        securesbom_host: ${{inputs.securesbom_host}}
        securesbom_api_key: ${{inputs.securesbom_api_key}}
post:
  shell: bash
  run: |
    rm -rf /tmp/reliza/*
